services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nusa-be:latest
    env_file:
      - .env-docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8004:8080"
    restart: unless-stopped
    networks:
      - nusa
    volumes:
      - "./storage:/var/www/html/storage"
      - "./bootstrap/cache:/var/www/html/bootstrap/cache"
    depends_on:
      redis:
        condition: service_healthy
  redis:
    env_file:
      - .env-docker
    image: "redis:alpine"
    ports:
      - "6383:6379"
    volumes:
      - "nusa-redis:/data"
    networks:
      - nusa
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
      
networks:
    nusa:
        driver: bridge

volumes:
    nusa-redis:
        driver: local
